### ISSUE TITLE
Help screen

### ISSUE THREAD

**Issue by Ilunaera** [LBRYFoundation/lbry-tipbot#10]
Can you change the help from this:

!tip
    balance: get your balance
    deposit: get address for your deposits
    withdraw ADDRESS AMOUNT: withdraw AMOUNT credits to ADDRESS
    [private] <user> <amount>: mention a user with @ and then the amount to tip them, or put private before the user to tip them privately.
    Key: [] : Optionally include contained keyword, <> : Replace with appropriate value.

to something like this:

http://prntscr.com/i2ehj2 

It's a link because I couldn't format it properly and it was annoying. Basically, remove the colons after the command (balance: -> balance) and have the description underneath indented. Same with the keys if possible, so it's easier to read and less easy to accidently make a mistake with

**Comment by nikooo777** [comment]
I approve of that, in addition I would add an example for the withdraw command rather than the techie parameters explanation.

I'll think of something!

By the way, if you want to keep the text formatted you can use ticks like this \``` one line before the block of text and one line after. or otherwise click on the <> icon in the editor after selecting the block of text.

```
   like
        this
```

**Comment by ProfessorDey** [comment]
I've created a pull request to solve this and also clean up the implementation of the help message and the channel warning, it should now be a bit clearer what's going on with the handling of such, though I suggest reading the full description at #12 

I wasn't quite sure what you meant by a less techy parameter explanation, so would need some suggestions there

**Comment by filipnyquist** [comment]
All off this Will also get changed in the new wunderbot targeting a release later this month

**Comment by ProfessorDey** [comment]
No harm in seeing if this works for now though I'd imagine. But good to know that Tipbot is being remerged into Wunderbot.

**Comment by nikooo777** [comment]
I think he means that the new wunderbot will also follow a similar path, however I don't expect nor want wunderbot to be the tipbot anymore.
Tipbot will remain a standalone project for the sake of simplicity and security. 

See my PR response for further info.

**Comment by filipnyquist** [comment]
@nikooo777 correct, the tipbot will stay as it is, with minimal updates except security updates.

**Comment by nikooo777** [comment]
as this issue is solved in #13 we'll have to wait for the other tasks also included in that PR to be finished. Once that's done that PR will be merged and this issue closed.

**Comment by nikooo777** [comment]
i just merged #13 so you can now observe the changes live.
Thank you :)
/closing
