### ISSUE TITLE
Odd bug when being tipped privately with tippers username

### ISSUE THREAD

**Issue by kcseb** [LBRYFoundation/lbry-tipbot#24]
When being tipped, the tipbot will have a weird bug with the username

Example: [12:55 PM] BOTtipbot: You have just been privately tipped 100 LBC by @jiggytom#jiggytom#7351.

Recreation Steps: Tip a user in private.

**Comment by ProfessorDey** [comment]
This should now be fixed and just needs a quick merge. Just involved editing the relevant strings.

**Comment by filipnyquist** [comment]
This is fixed in #25
