### ISSUE TITLE
Feature Request : Allow tipped User Via Private DM

### ISSUE THREAD

**Issue by ykris45** [LBRYFoundation/lbry-tipbot#26]
feedback on tipbot system,
this feature is very useful if we interact with users via private messages and when we give some tips to the user then it can not be in private messages, it would be nice if this can be immediately added to the next version.
Step to reproduce:
1. in private DM (eg I send a message to julie)
2. julie gives me 100 LBC, type! Tip <username> 100 in Private DM area.
3. can not tipped user.
it would be nice if you can give a tip via private DM. Thanks this is my feedback

**Comment by tzarebczan** [comment]
This is not possible, as the bot doesn't exist in the DM between you and other users. 

You can just DM the tipbot and send the tip that way...it's private.
