### ISSUE TITLE
Private Role tip broken

### ISSUE THREAD

**Issue by tzarebczan** [LBRYFoundation/lbry-tipbot#27]
Last PR attempted to fix the issue:
https://github.com/lbryio/lbry-tipbot/pull/20

```
[10:30 AM] Larva: !roletip @Trusted LBRYian 0.01
[10:30 AM] rouse: !roletip @Trusted LBRYian 1
[10:30 AM] Larva: Not work
```

**Comment by tzarebczan** [comment]
Roletip works now, but the private version is still broken.

**Comment by alyssaoc** [comment]
@tzarebczan Does this issue have a solution?

**Comment by tzarebczan** [comment]
No, and it's not that big of a deal since it's not used often (if at all). Going to give it a shot with  https://github.com/lbryio/lbry-tipbot/pull/33

**Comment by alyssaoc** [comment]
closing, Niko has fixed this
