### ISSUE TITLE
Tipbot does not reply to commands in DM

### ISSUE THREAD

**Issue by tzarebczan** [LBRYFoundation/lbry-tipbot#6]
@tzarebczan commented on [Mon Dec 18 2017](https://github.com/lbryio/lbry-wunderbot/issues/113)

When I message tipbot with !tip deposit or !tip help (From #bot-sandbox), I don't get a response. Another user complained about this as well. 

Can someone take a look into this? 

---

@filipnyquist commented on [Mon Dec 18 2017](https://github.com/lbryio/lbry-wunderbot/issues/113#issuecomment-352554139)

@nikooo777 could you take a look at this? you should have access to the server.

**Comment by nikooo777** [comment]
Tom, is this issue still relevant?

I know that tipbot will try to send a DM to the user, i'm not  aware of a fallback method if the user has DMs disabled.
